#pragma checksum "..\..\..\AnimationWheel\AnimationWheel.xaml" "{406ea660-64cf-4c82-b6f0-42d48172a799}" "D9F622AE361D5A85952FB6BB6209E830"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace SilverlightWordle {


    /// <summary>
    /// AnimationWheel
    /// </summary>
    public partial class AnimationWheel : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {


#line 5 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid LayoutRoot;

#line default
#line hidden


#line 9 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas Slice_1;

#line default
#line hidden


#line 10 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas Layer_1;

#line default
#line hidden


#line 11 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Canvas SpinWheel;

#line default
#line hidden


#line 12 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path;

#line default
#line hidden


#line 13 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_0;

#line default
#line hidden


#line 14 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_1;

#line default
#line hidden


#line 15 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_2;

#line default
#line hidden


#line 16 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_3;

#line default
#line hidden


#line 17 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_4;

#line default
#line hidden


#line 18 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_5;

#line default
#line hidden


#line 19 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_6;

#line default
#line hidden


#line 20 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_7;

#line default
#line hidden


#line 21 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_8;

#line default
#line hidden


#line 22 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_9;

#line default
#line hidden


#line 23 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_10;

#line default
#line hidden


#line 24 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_11;

#line default
#line hidden


#line 25 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_12;

#line default
#line hidden


#line 26 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_13;

#line default
#line hidden


#line 27 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_14;

#line default
#line hidden


#line 28 "..\..\..\AnimationWheel\AnimationWheel.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Path Path_15;

#line default
#line hidden

        private bool _contentLoaded;

        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Wordle;component/animationwheel/animationwheel.xaml", System.UriKind.Relative);

#line 1 "..\..\..\AnimationWheel\AnimationWheel.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);

#line default
#line hidden
        }

        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId) {
                case 1:
                    this.LayoutRoot = ((System.Windows.Controls.Grid)(target));
                    return;
                case 2:
                    this.Slice_1 = ((System.Windows.Controls.Canvas)(target));
                    return;
                case 3:
                    this.Layer_1 = ((System.Windows.Controls.Canvas)(target));
                    return;
                case 4:
                    this.SpinWheel = ((System.Windows.Controls.Canvas)(target));
                    return;
                case 5:
                    this.Path = ((System.Windows.Shapes.Path)(target));
                    return;
                case 6:
                    this.Path_0 = ((System.Windows.Shapes.Path)(target));
                    return;
                case 7:
                    this.Path_1 = ((System.Windows.Shapes.Path)(target));
                    return;
                case 8:
                    this.Path_2 = ((System.Windows.Shapes.Path)(target));
                    return;
                case 9:
                    this.Path_3 = ((System.Windows.Shapes.Path)(target));
                    return;
                case 10:
                    this.Path_4 = ((System.Windows.Shapes.Path)(target));
                    return;
                case 11:
                    this.Path_5 = ((System.Windows.Shapes.Path)(target));
                    return;
                case 12:
                    this.Path_6 = ((System.Windows.Shapes.Path)(target));
                    return;
                case 13:
                    this.Path_7 = ((System.Windows.Shapes.Path)(target));
                    return;
                case 14:
                    this.Path_8 = ((System.Windows.Shapes.Path)(target));
                    return;
                case 15:
                    this.Path_9 = ((System.Windows.Shapes.Path)(target));
                    return;
                case 16:
                    this.Path_10 = ((System.Windows.Shapes.Path)(target));
                    return;
                case 17:
                    this.Path_11 = ((System.Windows.Shapes.Path)(target));
                    return;
                case 18:
                    this.Path_12 = ((System.Windows.Shapes.Path)(target));
                    return;
                case 19:
                    this.Path_13 = ((System.Windows.Shapes.Path)(target));
                    return;
                case 20:
                    this.Path_14 = ((System.Windows.Shapes.Path)(target));
                    return;
                case 21:
                    this.Path_15 = ((System.Windows.Shapes.Path)(target));
                    return;
            }
            this._contentLoaded = true;
        }
    }
}

